services:
  - type: web
    name: CyberBot
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: rasa run --enable-api --cors "*" --port 5005
    pythonVersion: "3.10"  # Specify your desired Python version here
    port: 5005
